# Generated by Django 4.2.4 on 2023-10-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('name', models.CharField(max_length=100, null=True)),
                ('attack_priority', models.CharField(max_length=2, null=True)),
                ('longitude', models.CharField(max_length=100, null=True)),
                ('latitude', models.CharField(max_length=100, null=True)),
                ('enemy_organization', models.CharField(max_length=100, null=True)),
                ('target_goal', models.CharField(max_length=100, null=True)),
                ('was_target_destroyed', models.BooleanField(null=True)),
                ('target_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
