apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: my-namespace
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 30001
      targetPort: 8080