# Generated by Django 4.2.4 on 2023-12-13 12:41

from django.db import migrations, models
import django.db.models.deletion
import recipes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('ingredients', models.TextField()),
                ('preparation', models.TextField()),
                ('time', models.TimeField()),
                ('avg_starts', models.IntegerField(blank=True, validators=[recipes.models.validate_max])),
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_comments', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_comments', to='comments.comment')),
            ],
        ),
    ]
