# Generated by Django 4.2.4 on 2023-12-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='comments_number',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
