# Generated by Django 4.2.4 on 2023-12-13 14:41

from django.db import migrations, models
import django.db.models.deletion
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_initial'),
        ('recipes', '0002_recipe_comments_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='sum_stars',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='avg_starts',
            field=models.IntegerField(blank=True, editable=False, validators=[recipes.models.validate_max]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='comments_number',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_comments',
            field=models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_comments', to='comments.comment'),
        ),
    ]
