# Generated by Django 4.2.4 on 2023-12-14 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_initial'),
        ('recipes', '0004_alter_recipe_avg_starts_alter_recipe_comments_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_comments',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_comments', to='comments.comment'),
        ),
    ]
