# Generated by Django 4.2.4 on 2023-12-14 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_initial'),
        ('recipes', '0007_alter_recipe_recipe_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_comments',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_comments', to='comments.comment'),
        ),
    ]
