# Generated by Django 4.2.4 on 2023-12-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_initial'),
        ('recipes', '0008_alter_recipe_recipe_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_comments',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_comments',
            field=models.ManyToManyField(blank=True, default=None, editable=False, null=True, related_name='recipe_comments', to='comments.comment'),
        ),
    ]
