# Generated by Django 4.2.4 on 2023-12-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_remove_recipe_recipe_comments_recipe_recipe_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='level',
            field=models.CharField(default='beginner', max_length=50),
        ),
        migrations.AddField(
            model_name='recipe',
            name='type',
            field=models.CharField(default='other', max_length=50),
        ),
    ]
