# Generated by Django 4.2.4 on 2023-12-21 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_recipe_level_recipe_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='avg_starts',
            new_name='avg_stars',
        ),
    ]
