# Generated by Django 4.2.4 on 2023-12-23 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_rename_avg_starts_recipe_avg_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='avg_stars',
        ),
    ]
