# Generated by Django 4.2.4 on 2023-10-24 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_date', models.DateField()),
                ('close_date', models.DateField()),
                ('report_username', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('closed', 'Closed'), ('open', 'Open'), ('waiting for response', 'Waiting for response'), ('waiting for treatment', 'Waiting for treatment')], max_length=255)),
                ('can_open_event', models.BooleanField(default=False)),
                ('can_download_event', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChatForm',
            fields=[
                ('form_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forms.form')),
            ],
            bases=('forms.form',),
        ),
        migrations.CreateModel(
            name='FileForm',
            fields=[
                ('form_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forms.form')),
            ],
            bases=('forms.form',),
        ),
    ]
