# Generated by Django 4.2.4 on 2023-10-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms', '0001_initial'),
        ('users', '0001_initial'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='users',
            field=models.ManyToManyField(related_name='form_users', to='users.user'),
        ),
        migrations.AddField(
            model_name='fileform',
            name='files',
            field=models.ManyToManyField(related_name='form_files', to='message.file'),
        ),
        migrations.AddField(
            model_name='chatform',
            name='messages',
            field=models.ManyToManyField(related_name='form_messages', to='message.message'),
        ),
    ]
