# Generated by Django 4.2.4 on 2023-10-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_remove_chat_messages_chat_messages'),
        ('forms', '0003_alter_form_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatform',
            name='messages',
        ),
        migrations.AddField(
            model_name='chatform',
            name='chats',
            field=models.ManyToManyField(related_name='form_chats', to='chats.chat'),
        ),
    ]
