# Generated by Django 4.2.4 on 2023-12-14 11:40

import comments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='stars',
            field=models.IntegerField(default=1, validators=[comments.models.validate_max]),
        ),
    ]
