# Generated by Django 4.2.4 on 2023-12-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comment_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.TextField(),
        ),
    ]
