# Generated by Django 4.2.4 on 2023-10-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_message_receiver_alter_file_id_alter_message_id_and_more'),
        ('users', '0002_alter_user_unread_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unread_messages',
            field=models.ManyToManyField(blank=True, related_name='unread_messages', to='message.message'),
        ),
    ]
