# Generated by Django 4.2.4 on 2023-10-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parents', to='people.person'),
        ),
    ]
