apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-service
  namespace: my-namespace
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 30001 
      targetPort: 8080
