# Generated by Django 4.2.4 on 2023-10-24 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_chat_messages'),
        ('message', '0004_message_receiver_alter_file_id_alter_message_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.AlterField(
            model_name='message',
            name='chat_pointer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chats.chat'),
        ),
    ]
