# Generated by Django 4.2.4 on 2023-10-19 11:16

from django.db import migrations, models
from django.core.validators import MaxValueValidator

def round_up_int(apps, schema_editor):
    Parent = apps.get_model('people', 'Parent')
    for parent in Parent.objects.all():
        parent.salary = int(parent.salary)
        parent.save()

class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_alter_parent_children'),
    ]

    operations = [
        migrations.RunPython(round_up_int),
        migrations.AlterField(
            model_name='parent',
            name='salary',
            field = models.IntegerField(MaxValueValidator(999999)),
        ),
    ]

#IntegerField

#we need to run python3 manage.py migrate people 0004_auto_20231019_1116