# Generated by Django 4.2.4 on 2023-10-24 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_message_receiver_alter_file_id_alter_message_id_and_more'),
        ('chats', '0002_chat_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='messages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='message.message'),
        ),
    ]
