# Generated by Django 4.2.4 on 2023-10-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_remove_message_receiver_alter_message_chat_pointer'),
        ('chats', '0003_alter_chat_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='messages',
        ),
        migrations.AddField(
            model_name='chat',
            name='messages',
            field=models.ManyToManyField(blank=True, null=True, related_name='chat_messages', to='message.message'),
        ),
    ]
