version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_USER: ${MYSQL_USER}
      MYSQL_DATABASE: myDB
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
        
  api:
    build: .
    container_name: api
    restart: always
    ports:
      - "4000:4000" #its 4000 insted of 5000 because the airplay in apple uses the port 5000
    depends_on:
      - mysql
    command: ["dockerize", "-wait", "tcp://mysql:3306", "-timeout", "20s", "python", "/app/api.py"]

networks:
  api:
    driver: bridge