# Generated by Django 4.2.4 on 2023-12-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=15)),
                ('password', models.TextField()),
                ('birthday', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('id', models.PositiveIntegerField(max_length=9, primary_key=True, serialize=False, unique=True)),
                ('my_recipes', models.ManyToManyField(blank=True, related_name='favorite_recipes', to='recipes.recipe')),
            ],
        ),
    ]
